name: BTAX Test CICD

on:
  schedule:
    - cron: '0 10 * * *' # every day at 00:00 UTC
  workflow_dispatch: {} # manual trigger

jobs:
  addAsset:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
      - name: addAsset
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }} 
          API_KEY: ${{ secrets.API_KEY }} 
        run: |
          pip install -r requirements.txt
          pytest tests/test_add_asset.py
  delsset:
    runs-on: ubuntu-slim
    needs: addAsset
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
      - name: addAsset
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }} 
          API_KEY: ${{ secrets.API_KEY }} 
        run: |
          pip install -r requirements.txt
          pytest tests/test_del_asset.py
  sellAsset:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
      - name: sellAsset
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }} 
          API_KEY: ${{ secrets.API_KEY }} 
        run: |
          pip install -r requirements.txt
          pytest tests/test_sell_asset.py
          pytest tests/test_sell_gbp_asset.py
          pytest tests/test_sell_usd_asset.py